### ISSUE TITLE
当仓库的地址有端口时, 会出现一些小问题

### ISSUE THREAD

**Issue by ruke318** [wi1dcard/weekly-report#1]
从文档表格中链接跳转到修改记录的时候url没有端口

**Comment by wi1dcard** [comment]
远端仓库的地址是什么？`git remote -v` 看一下。

根据你不完整的描述，猜测你说的「跳转」是通过仓库地址正则匹配出来的，所以无法获得 HTTP 协议的端口，只能按照默认处理。

**Comment by ruke318** [comment]
> 远端仓库的地址是什么？`git remote -v` 看一下。
> 
> 根据你不完整的描述，猜测你说的「跳转」是通过仓库地址正则匹配出来的，所以无法获得 HTTP 协议的端口，只能按照默认处理。

嗯, 木有问题, 我看了代码, 通过命令没法拿到端口,  自己配置文件配置就好了

**Comment by wi1dcard** [comment]
@ruke318 好的，感谢关注，有任何问题欢迎补充。
